docs: improve external-api documentation
lukso-network/docs pull request #1107
Opened 2024-08-01 10:16 UTC by magalimorin18

DEV-11279

2024-08-01 10:16 UTC, Hugoo commented
Task linked: [DEV-11279 Improve swagger with more explanation on how to generate the PostDeploymentCallData](https://app.clickup.com/t/2645698/DEV-11279)

2024-08-01 12:32 UTC, CJ42 requested changes

2024-08-01 12:32 UTC, CJ42 commented on docs/tools/relayer-developer.md
> +ℹ️ More info on [VerifiableURI](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#verifiableuri)
```suggestion
ℹ️ More info on [`VerifiableURI`](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#verifiableuri)
```

2024-08-01 12:32 UTC, CJ42 commented on docs/tools/relayer-developer.md
> +```javascript title="postDeploymentCallData: Call data which will be executed on the ERC725Account contract after deployment. Should contain the encoded setData transaction to set required permission
Is it not setDataBatch?

```suggestion
```javascript title="postDeploymentCallData: Calldata which will be executed on the ERC725Account contract after deployment. Should contain the encoded setDataBatch transaction to set the initial permissions and LSP3 Profile Data"
```

2024-08-01 12:32 UTC, CJ42 commented on docs/tools/relayer-developer.md
> +#### How it works
This will not show this section in the sidebar with 4 

```suggestion
### How it works
```

2024-08-12 10:17 UTC, magalimorin18 commented on docs/tools/relayer-developer.md
> +  <summary>OPTION 1: lsp6ControllerAddress & lsp3Profile</summary>
I would prefer to keep details here so the main page stays concise and if developers want more info they can open the details drop down

2024-08-12 10:53 UTC, richtera approved these changes

2024-08-13 11:35 UTC, CJ42 approved these changes

2024-08-13 11:35 UTC, merged