Overview Page on Mobile
lukso-network/docs pull request #1167
Opened 2024-11-18 14:02 UTC by mustafademiray

before:
![image](https://github.com/user-attachments/assets/05d03de5-ef9a-415f-846f-1355b665728d)

![image](https://github.com/user-attachments/assets/c785b82d-39e0-45f2-a96c-03a942bd4346)

after:
![image](https://github.com/user-attachments/assets/7eb3e080-21b7-4c15-aec2-19658e542af9)

![image](https://github.com/user-attachments/assets/d7b34ab9-ba1e-42a1-9ac6-b6421cb729d7)

2024-11-18 15:27 UTC, JeneaVranceanu requested changes
Something is wrong with the number 2. It's squashed. 

![Screenshot 2024-11-18 at 17 26 56](https://github.com/user-attachments/assets/bab86c4a-c2ac-4a27-9d06-24b6e18cacc5)

2024-11-19 12:36 UTC, JeneaVranceanu approved these changes

2024-11-20 10:10 UTC, CJ42 approved these changes

2024-11-20 10:10 UTC, CJ42 commented on docs/learn/getting-started.md
> +    text="Install the UP Browser Extension🧩"
Missing space before the emoji

```suggestion
    text="Install the UP Browser Extension 🧩"
```

2024-11-20 10:10 UTC, CJ42 commented on src/components/CardWithImage/index.tsx
> +              xs: '100%', // full width on mobile
that's super clean! 🫡

2024-11-20 11:15 UTC, merged