add ClaimOwnership in contract API docs + LSP0
lukso-network/docs pull request #215
Opened 2022-05-24 16:27 UTC by CJ42

# What does this PR introduce?

- [x] add description of functions `pendingOwner()` and `claimOwnership()`in API docs for LSP0 and LSP9
- [x] add section for ClaimOwnership in LSP0

2022-05-26 10:38 UTC, fhildeb requested changes

2022-05-26 10:38 UTC, fhildeb commented on docs/standards/universal-profile/lsp0-erc725account.md
> +**ClaimOwnership** is a modified version of [EIP173 - Contract Ownership Standard](https://eips.ethereum.org/EIPS/eip-173), that uses a safer mechanism for transferring ownership.
```suggestion
**ClaimOwnership** is a modified version of [EIP173 - Contract Ownership Standard](https://eips.ethereum.org/EIPS/eip-173) that uses a safer mechanism for transferring ownership.
```

2022-05-26 10:38 UTC, fhildeb commented on docs/standards/universal-profile/lsp0-erc725account.md
> +In EIP713, ownership of a contract is transferred directly to a new owner, potentially leading to blocking access to the contract. For instance, if the owner call `transferOwnership()` and the new ow
```suggestion
In EIP713, ownership of a contract is transferred directly to a new owner, potentially leading to blocking access to the contract. For instance, if the owner calls `transferOwnership()` and the new owner:
```

2022-05-26 10:38 UTC, fhildeb commented on docs/standards/universal-profile/lsp0-erc725account.md
> +1. The previous owner transfer ownership to a new owner via the [`transferOwnership()`](./../smart-contracts/lsp0-erc725-account.md#transferownership) function.
```suggestion
1. The previous owner transfers ownership to a new owner via the [`transferOwnership()`](./../smart-contracts/lsp0-erc725-account.md#transferownership) function.
```

2022-05-26 16:59 UTC, fhildeb approved these changes

2022-05-28 10:03 UTC, YamenMerhi approved these changes

2022-05-31 09:47 UTC, merged