Create a page for LSP1 Type IDs
lukso-network/docs pull request #681
Opened 2023-10-16 12:59 UTC by b00ste

# What does this PR introduce?

In this PR we create a page that contains all the LSP1 Type IDs

2023-10-16 12:59 UTC, Hugoo commented
Task linked: [DEV-8623 Add Type IDs list to the `docs.lukso.tech`](https://app.clickup.com/t/2645698/DEV-8623)

2023-10-16 12:59 UTC, Hugoo commented
Task linked: [DEV-8623 Add Type IDs list to the `docs.lukso.tech`](https://app.clickup.com/t/2645698/DEV-8623)

2023-10-16 12:59 UTC, Hugoo commented
Task linked: [DEV-8623 Add Type IDs list to the `docs.lukso.tech`](https://app.clickup.com/t/2645698/DEV-8623)

2023-10-18 09:36 UTC, CJ42 requested changes
Could you please add the path to this file in the `sidebar.js` file, so that this page shows in the docs.

<img width="881" alt="image" src="https://github.com/lukso-network/docs/assets/31145285/a47bd92b-d206-4fe4-ae21-713f25862dd4">

2023-10-18 09:36 UTC, CJ42 commented on docs/contracts/type-ids.md
> +title: Interfaces IDs
```suggestion
title: Universal Receiver Type IDs
```

2023-10-18 09:46 UTC, skimaharvey approved these changes

2023-10-18 09:55 UTC, merged