update create lsp8 collection with version 0.13.0
lukso-network/docs pull request #748
Opened 2023-11-28 10:12 UTC by skimaharvey

# What does this PR introduce?

Update the `create-nft-collection-lsp8` page so that it works with the new contract version (`0.13.0`)

**N.B:** Do not merge before the release of 0.13.0

2023-12-11 11:29 UTC, CJ42 requested changes
added review comments

2023-12-11 17:10 UTC, fhildeb approved these changes

2023-12-12 09:06 UTC, Hugoo approved these changes

2023-12-14 09:11 UTC, Hugoo approved these changes

2023-12-14 09:11 UTC, merged