Add IPFS gateways
lukso-network/docs pull request #800
Opened 2024-01-03 18:35 UTC by fhildeb

## What does this PR introduce?

Adds the **IPFS gateways** for testnet and mainnet to the **network parameter lists**.

Previously, these addresses have been used in various guides and the playground already, like:

Mentioned Upload RPCs: 
- `https://docs.lukso.tech/learn/expert-guides/universal-profile/edit-profile/`
- `https://github.com/lukso-network/lukso-playground/blob/main/README.md`

Mentioned Download RPCs:
- `https://docs.lukso.tech/learn/dapp-developer/read-profile-data/`
- `https://docs.lukso.tech/learn/dapp-developer/standard-detection`
- `https://docs.lukso.tech/learn/expert-guides/read-asset-data/`
- `https://docs.lukso.tech/learn/expert-guides/universal-profile/edit-profile/`
- `https://github.com/lukso-network/lukso-playground/blob/main/README.md`

2024-01-03 18:43 UTC, Hugoo requested changes

2024-01-03 18:43 UTC, Hugoo commented on docs/networks/mainnet/parameters.md
> +- IPFS Upload: `api.2eff.lukso.dev`
This one is linked to our old super legacy IPFS cluster which we will shutdown in the coming weeks once the asset migration to mainnet is over.

This cluster has sharing issues (files upload there are not properly dispatched to other IPFS clusters).

Therefore, I recommend to not put this here and to tell users to get their own IPFS gateways (pinata, infura etc.)

2024-01-03 18:43 UTC, Hugoo commented on docs/networks/mainnet/parameters.md
> +- IPFS Download: `https://api.universalprofile.cloud/ipfs`
We should encourage developers to figure out their own IPFS gateways. We can not support IPFS delivery for the whole community.

Now that our new gateway is propagating files correctly - people can use any IPFS providers (infura pinata etc.) To correctly fetch the assets.

Therefore I recommend to not advertise these URLs here or at the very least to add a warning:

This is for development purposes only. We do not guarantee any SLA and we can add rate limits. You are highly encouraged to get your own IPFS gateway (infura, pinata etc.)

2024-01-04 08:23 UTC, fhildeb commented
Applied suggestions. I just checked- Infura does not allow custom RPC endpoints anymore. So I left it out of the applied suggestions.

2024-01-04 10:52 UTC, Hugoo approved these changes

2024-01-04 10:52 UTC, merged