Update LSP6 Permission Guide
lukso-network/docs pull request #898
Opened 2024-02-16 18:33 UTC by fhildeb

2024-02-19 11:29 UTC, Hugoo requested changes
i think this needs some more time - i saw a "L16 network" occurence - i guess this was done too fast.

2024-02-19 11:29 UTC, Hugoo commented on docs/learn/expert-guides/key-manager/get-controller-permissions.md
> +First, we will install the 🛠️[`erc725.js`](../../../tools/erc725js/getting-started.md) library to easily query and decode the 🗂️[ERC725Y data storage](../../../standards/lsp-background/erc725.md#erc7
L16 network, really?

2024-02-19 11:30 UTC, Hugoo commented on docs/learn/expert-guides/key-manager/get-controller-permissions.md
> +// Set up Universal Profile on the LUKSO Testnet
This is not really correct - it doesn't setup anything on the testnet. Maybe more

"Instantiate erc725.js with a Universal Profile address" or smtgh makes more sense

2024-02-19 11:32 UTC, Hugoo commented on docs/learn/expert-guides/key-manager/get-controller-permissions.md
> +    <summary>Show <code>AddressPermissions[]</code> value</summary>
I would keep this close to the code, it is the value of "result" (which btw could be renames to "permissions"

<img width="671" alt="image" src="https://github.com/lukso-network/docs/assets/477945/bbb208c4-0418-4ad0-b298-7a09bb2c09f1">

The output is quite small so im not sure we even need a Details box.

Btw, please use `<details>` as the issue with this is gone (revert to previous version of react mdx)

2024-02-19 11:33 UTC, Hugoo commented on docs/learn/expert-guides/key-manager/get-controller-permissions.md
> +    <summary>Show <code>AddressPermissions[]</code> value</summary>
im not sure these emojis 🗂️ are really needed here, same for 🛠️

2024-02-19 11:33 UTC, Hugoo commented on docs/learn/expert-guides/key-manager/get-controller-permissions.md
> +```
is this js code? 🤔 

<img width="107" alt="image" src="https://github.com/lukso-network/docs/assets/477945/f538abbd-8521-41a4-9ede-dd30a7b20a3b">

<img width="697" alt="image" src="https://github.com/lukso-network/docs/assets/477945/2836d677-bea9-4a5b-8ac2-1873c4ae098d">

2024-02-19 18:11 UTC, fhildeb commented
Thanks for the feedback. I should not have missed the L16 appearance. Will remind myself to do better self-reviews.

Applied all suggestions, changed naming, and included small outputs into the code 👍🏻
Also updated the related playground code ✅

2024-02-20 09:17 UTC, Hugoo approved these changes

2024-02-20 09:17 UTC, merged