Update LSP6 relay call guide
lukso-network/docs pull request #909
Opened 2024-02-23 18:42 UTC by fhildeb

Todo:

- [ ] Test script in playground
- [ ] Grammar checks

2024-02-28 18:25 UTC, CJ42 commented on docs/learn/expert-guides/key-manager/execute-relay-transactions.md
> +Even when relaying the transaction using a third-party, you will need execute permission is necessary. Otherwise, unauthorized parties would be able to send transactions to your relayer address.
Suggest adding link to the permission in the LSP6 standard page. And remove the 2nd sentence which contradicts the first.

```suggestion
To execute relay transactions using a third-party add, you will need the `EXECUTE_RELAY_CALL` permission.
```

2024-03-01 17:36 UTC, Hugoo commented
@fhildeb what is the status on that PR?

2024-03-05 09:37 UTC, fhildeb commented
Ready to be merged- tested and applied grammar checks & suggestions from Jean.

Related playground PR: https://github.com/lukso-network/lukso-playground/pull/52

2024-03-07 04:19 UTC, CJ42 requested changes

2024-03-07 04:19 UTC, CJ42 commented on docs/learn/expert-guides/key-manager/execute-relay-transactions.md
> +After installation, we can import the contract artifacts and set up relevant constants. To encode the transaction, you need the address of the Universal Profile smart contract and the private key of
Suggest rewording back to how it was, and maybe add 1 extra sentence:

```suggestion
To encode a transaction, we need the address of the Universal Profile smart contract and the private key of a controller key with sufficient [LSP6 permissions](../../../standards/universal-profile/lsp6-key-manager.md#permissions) to execute the transaction.
First, create an instance of the Universal Profile contract and its Key Manager.
```

2024-03-07 04:19 UTC, CJ42 commented on docs/learn/expert-guides/key-manager/execute-relay-transactions.md
> +:::caution Caution when using a Private Key
This is a good callout 👌 . Would even put that in danger.

```suggestion
:::danger Caution when using your controller's Private Key
```

2024-03-07 04:19 UTC, CJ42 commented on docs/learn/expert-guides/key-manager/execute-relay-transactions.md
> +// Instanciate EIP191 Signer
```suggestion
// Instantiate EIP191 Signer
```

2024-03-07 04:19 UTC, CJ42 commented on docs/learn/expert-guides/key-manager/execute-relay-transactions.md
> +/**
Suggest removing this code comment block for brevity. The code and function parameters are self explanatory themselves.

2024-03-07 04:19 UTC, CJ42 commented on docs/learn/expert-guides/key-manager/execute-relay-transactions.md
> +- **`nonce` of the controller**: This value can be retrieved by calling the [`getNonce`](../../../contracts/contracts/LSP6KeyManager/LSP6KeyManager.md#getnonce) function on the [Key Manager](../../..
The nonce can be from an EOA or a contract. Suggest removing this

```suggestion
- **`nonce` of the controller**: can be retrieved via the [`getNonce`](../../../contracts/contracts/LSP6KeyManager/LSP6KeyManager.md#getnonce) function on the [Key Manager](../../../standards/universal-profile/lsp6-key-manager.md) associated with the Universal Profile.
```

2024-03-07 10:40 UTC, fhildeb commented
Thanks for the review, good input. 🙏🏻 Applied suggestions and grammar on code snippets.

> Regarding client-side/server-side differentiation: I initially wanted to point out that executing a relay call involves two steps: preparation on the client side and deployment on the server/relay service. However, I agree that the bullet point list caused more confusion—a clear sentence fits much better. We don't have to state that relay services are server-side. ✅

2024-03-11 12:54 UTC, CJ42 approved these changes

2024-03-11 12:54 UTC, merged