Update LSP12 Issued Asset Guides
lukso-network/docs pull request #943
Opened 2024-04-10 16:09 UTC by fhildeb

## PR Features:

- Adds dynamic asset encoding to the issued asset guides (separate menu for setting and updating)
- Adds description for referencing assets on a UP
- Links to new playground snippets
- Simplifies heading + adds Emoji

## Discussion

@b00ste We currently have two pages for issued assets that are almost similar (90%). One is for dApp developers, and one is the backend- the only difference being how to interact (either using an extension request or private key) 

WDYT about keeping only the dApp guide? The code within `lukso-playground` uses a private key anyway. Experts will also know how to exchange the extension provider for a private key. IMO, it's nothing LUKSO-related.

2024-04-11 12:20 UTC, CJ42 requested changes

2024-04-11 12:20 UTC, CJ42 commented on docs/learn/dapp-developer/register-lsp12-issued-assets.md
> +During the [creation of an asset](./deploy-contracts.md), Universal Profiles can be referenced as creators within the [LSP4 Metadata](../../standards/tokens/LSP4-Digital-Asset-Metadata.md). To **auth
```suggestion
During the [creation of an asset](./deploy-contracts.md), Universal Profiles can be referenced as creators within the [LSP4 Metadata](../../standards/tokens/LSP4-Digital-Asset-Metadata.md). To **authenticate the creators** of an asset, their Universal Profiles must list the asset's address under the [LSP12 Issued Assets](../../standards/universal-profile/lsp12-issued-assets.md). Services can then validate the **on-chain cross-link** to prove authenticity.
```

2024-04-11 12:20 UTC, CJ42 commented on docs/learn/dapp-developer/register-lsp12-issued-assets.md
> +After setting up the array of assets, you can use the [`erc725.js`](../../tools/erc725js/getting-started.md) library and the [LSP12 JSON Schema](../../standards/universal-profile/lsp12-issued-assets/
```suggestion
After setting up the array of assets, you can use the [`erc725.js`](../../tools/erc725js/getting-started.md) library to encode the [`LSP12IssuedAssets[]`](../../standards/universal-profile/lsp12-issued-assets/) data keys. There are two ways to encode data:
```

2024-04-11 12:20 UTC, CJ42 commented on docs/learn/dapp-developer/register-lsp12-issued-assets.md
> +- **add, update, or remove existing issued assets**: If the Universal Profile already has issued assets, and you want to add, update, or remove certain assets, you can provide the `startingIndex` and
```suggestion
- **add, update, or remove existing issued assets**: If the Universal Profile already has issued assets, and you want to add, update, or remove certain assets, you can provide the `startingIndex` and `totalArrayLength` parameters. Therefore, your prepared array only represents a subset of all the issued assets listed in your Universal Profile.
```

2024-04-11 12:20 UTC, CJ42 commented on docs/learn/dapp-developer/register-lsp12-issued-assets.md
> +    <TabItem value="ethersjs" label="ethers.js">
```suggestion
    <TabItem value="ethersjs" label="ethers.js" default>
```

2024-04-11 12:20 UTC, CJ42 commented on docs/learn/expert-guides/universal-profile/register-lsp12-issued-assets.md
why is there the same guide twice?

2024-04-11 12:20 UTC, CJ42 commented on docs/learn/expert-guides/universal-profile/register-lsp12-issued-assets.md
> +Updating a subset of storage elements in an array requires dynamic encoding, which is only available for [`erc725.js`](../../../tools/erc725js/getting-started.md) of version 0.24.0 and above.
I don't think we need to mention this. People will always the latest version of the _erc725.js_ library. Suggest removing

2024-04-12 08:18 UTC, fhildeb commented
- Applied Suggestions
- Removed similar backend guide

LGTM

2024-04-15 09:47 UTC, CJ42 approved these changes

2024-04-15 09:57 UTC, merged