Add CascadeUploader part at IPFS Upload Section
lukso-network/docs pull request #989
Opened 2024-05-24 12:13 UTC by mastercodercat

Updated IPFS Upload Section regarding to new plugin - data-provider-cascade.

2024-05-24 12:37 UTC, Hugoo approved these changes
Cool thanks!

2024-05-24 12:37 UTC, Hugoo commented on docs/learn/expert-guides/utilize-ipfs-storage.md
> +To use IPFS as a file service through _Pinata_, _Infura_ and _Csacade_ you will have to:
```suggestion
To use IPFS as a file service through _Pinata_, _Infura_ and _Cascade_ you will have to:
```

2024-05-24 12:40 UTC, Hugoo commented on docs/learn/expert-guides/utilize-ipfs-storage.md
> +import { CascadeUploader } from '@lukso/data-provider-cascade';
I can't find that lib on NPM?

https://www.npmjs.com/search?q=%40lukso%2Fdata-provider-cascade

2024-05-24 12:41 UTC, Hugoo requested changes
Adding the RC. See questions in the reviews.

2024-05-24 12:42 UTC, Hugoo commented on docs/learn/expert-guides/utilize-ipfs-storage.md
> +3. **Upload your File Content**: Utilize the [LUKSO network tools for data providers](https://github.com/lukso-network/tools-data-providers) to upload content. You can upload directly to Pinata using
```suggestion
3. **Upload your File Content**: Utilize the [LUKSO network tools for data providers](https://github.com/lukso-network/tools-data-providers) to upload content. You can upload directly to Pinata using your Pinata credentials or to the proxy with the shared secret. And also by using Cascade API key, you can upload to Cascade protocol directly.
```

2024-05-24 12:43 UTC, Hugoo commented on docs/learn/expert-guides/utilize-ipfs-storage.md
> +import { CascadeUploader } from '@lukso/data-provider-cascade';
Related to: https://github.com/lukso-network/tools-data-providers/pull/12

2024-05-24 12:43 UTC, Hugoo commented
https://github.com/lukso-network/tools-data-providers/pull/12

2024-05-24 12:44 UTC, Hugoo commented
Let's merge this on the lib has been published?

2024-06-04 08:00 UTC, Hugoo commented
Waiting for https://github.com/lukso-network/tools-data-providers/pull/12 to be merged and released - @richtera

2024-06-10 16:06 UTC, CJ42 requested changes
We should put this on hold until we have the sub-package from the tool-data-provider released. @richtera

2024-07-11 10:08 UTC, CJ42 commented
@mastercodercat the CI is failing and there are merge conflicts. Could you fix them please so that we can merge? :)

2024-07-29 15:41 UTC, closed without merging